version: '3'
services:
  web:
    restart: always
    ports:
      - 80:3000
    build:
      args:
        app_env: production

  api:
    restart: always
    build:
      args:
        app_env: production

  db:
    restart: always