version: '3'
services:
  img:
    build:
      context: ./img
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./img:/app
    ports:
      - 5000:5000
  web:
    build:
      context: ./web
      args:
        app_env: ${APP_ENV}
    depends_on:
      - api
    volumes:
      - ./web/src:/web/src 
      - ./web/public:/web/public
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    depends_on:
      - db
    volumes:
      - ./api:/go/src/github.com/chrfrasco/sharing-wall/api
    ports:
      - 8080:8080

  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
